all: main

main: linked_list.o main.o 
	gcc -Wall -o main linked_list.o main.o
	
linked_list.o: linked_list.h linked_list.c
	gcc -Wall -c linked_list.c

main.o: linked_list.h main.c
	gcc -Wall -c main.c

compileonly: linked_list.o main.o

deleteofiles:
	del /q *.o
	
deleteexec:
	del /q main.exe

deleteall: deleteexec deleteofiles
